[package]
name = "pylon-gateway-pool"
version = "0.1.1"
authors = ["carter <carter@pylon.money>"]
edition = "2018"
description = "Pylon Gateway's pool contract"
license = "Apache-2.0"
repository = "https://github.com/pylon-protocol/pylon-gateway-contracts"
homepage = "https://pylon.money"
documentation = "https://docs.pylon.money"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[profile.dev]
overflow-checks = true

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw2 = { version = "0.9.1" }
cw20 = { version = "0.9.1" }
terraswap = "2.4.0"
terra-cosmwasm = "2.2.0"
thiserror = "1.0"
pylon-gateway = { version = "0.2.0", path = "../../packages/pylon_gateway" }
pylon-utils = { version = "0.2.0" }
cosmwasm-bignumber = "2.2.0"
cosmwasm-std = { version = "0.16.3" }
cosmwasm-storage = { version = "0.16.3" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
snafu = { version = "0.6.3" }
protobuf = { version = "2", features = ["with-bytes"] }

[dev-dependencies]
cosmwasm-schema = { version = "0.16.3" }
